package com.jkmodel.store;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
@EnableWebSecurity
public class JkmodelApplication {

    public static void main(String[] args) {
        SpringApplication.run(JkmodelApplication.class, args);
    }

}
